name: Go

on: [push]

jobs:
  build:
    runs-on: carbonrunner-1vcpu-ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.3
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go test -v .
